services:
  - type: web
    name: fender
    runtime: node
    buildCommand: pip install -r requirements.txt && npm install && cd frontend && npm install && npm run build && cd ..
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
